// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMarkdownToDocx(arg1:string,arg2:string):Promise<string>;

export function GetFileName(arg1:string):Promise<string>;

export function GetSuggestedExportName(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;
