// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMarkdownToDocx(arg1, arg2) {
  return window['go']['main']['App']['ExportMarkdownToDocx'](arg1, arg2);
}

export function GetFileName(arg1) {
  return window['go']['main']['App']['GetFileName'](arg1);
}

export function GetSuggestedExportName(arg1) {
  return window['go']['main']['App']['GetSuggestedExportName'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}
